import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import Geist Sans and Mono locally
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Make sure the path matches your font file
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Make sure the path matches your font file
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
